backend:
  name: github
  repo: develijahlee/yonseiuicscribe

media_folder: src/content/posts/images
public_folder: ./images

collections:
  - name: uicscribe
    label: Blog Post
    folder: src/content/posts
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: author, widget: string }
      - { name: date, label: Date (YYYY-MM-DD), dateFormat: "YYYY-MM-DD", timeFormat: false, widget: "datetime" }
      - { name: category, label: Category (Capitalize first letter), widget: string }
      - { name: featuredImage, label: Thumbnail Image File Name (change spaces into dashes), widget: string, default: ./images/ }
      - { name: featured, label: Featured (Enter true without capitalization for article to be featured. Leave false if not.), widget: string, default: "false" }
      - { name: body, label: Body (Insert image first. Close image tab. Add text under image.), widget: markdown }